### ISSUE TITLE
RuntimeError in running test_case.py

### ISSUE THREAD

**Issue by HanLab-OSU** [ddd9898/DeepNano#3]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DeepNano_seq:
	Unexpected key(s) in state_dict: "pretrained_model.embeddings.position_ids". 
help please? Thanks

**Comment by ddd9898** [comment]
Hi Hanlab-OSU,
This bug currently looks as if it is related to huggingface transfermors. Could you please provide more details? For example: does this bug only appear when running test_case.py? Or does it appear when running both test_nai.py and test_ppi_ESM2.py? Are you using the 8M version of the DeepNano-seq model?

**Comment by HanLab-OSU** [comment]
It occurs for test_nai.py as well. yes I was using the 8M version of the DeepNano-seq model. Thanks. 
##########################在nai数据上测试DeepNano-seq(DScriptData)esm2_t6_8M_UR50D模型：
Some weights of EsmModel were not initialized from the model checkpoint at ./models/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/xx/DeepNano/test_nai.py", line 89, in <module>
    model.load_state_dict(weights)
  File "/home/xx/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DeepNano_seq:
	Unexpected key(s) in state_dict: "pretrained_model.embeddings.position_ids".

**Comment by HanLab-OSU** [comment]
I finally got it to work by installing the requirement.txt and torch=1.13.1+cu116. Also i need to downgrade numpy to 1.26.4

**Comment by ddd9898** [comment]
I tested and found that this bug is related to the version of huggingface transformers. The bug occurs in versions 4.31.0 and above, while it does not occur in version 4.30.2 and below. Thank you, I have updated the readme.md to clarify this issue.
