### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Jnuvenu** [ddd9898/DeepNano#4]
Thank you for the great project, I meet some bug when I try the following command:
Virtual screening of anti-HSA and anti-GST:
python test_case.py
python test_background.py  --size 100w

my system:
ubuntu 24
GPU:24G
CUDA:12.4

(deepnano) $ python test_case.py
python test_background.py  --size 100w
...
##########################在humanHSA background数据上测试DeepNano-seq(DScriptData)_esm2_t6_8M_UR50D模型：
Some weights of the model checkpoint at ./models/esm2_t6_8M_UR50D were not used when initializing EsmModel: ['lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing EsmModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing EsmModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of EsmModel were not initialized from the model checkpoint at ./models/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                | 1/3907 [00:01<1:17:59,  1.20s/it]
Traceback (most recent call last):
  File "/home/zhike/WJM/DeepNano/test_background.py", line 142, in <module>
    g,p_ave,p_min,p_max = predicting(model, device, test_loader,Model_type=3)
  File "/home/zhike/WJM/DeepNano/test_background.py", line 57, in predicting
    p_ave, p_min, p_max = model(seqs_nanobody,seqs_antigen,device)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/WJM/DeepNano/models/models.py", line 140, in forward
    temp_output2=self.pretrained_model(input_ids=input_ids2,attention_mask=attention_mask2)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/transformers/models/esm/modeling_esm.py", line 922, in forward
    encoder_outputs = self.encoder(
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/transformers/models/esm/modeling_esm.py", line 622, in forward
    layer_outputs = layer_module(
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/transformers/models/esm/modeling_esm.py", line 507, in forward
    self_attention_outputs = self.attention(
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/transformers/models/esm/modeling_esm.py", line 441, in forward
    self_outputs = self.self(
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhike/miniforge3/envs/deepnano/lib/python3.9/site-packages/transformers/models/esm/modeling_esm.py", line 365, in forward
    attention_scores = attention_scores + attention_mask
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.07 GiB. GPU 0 has a total capacity of 23.62 GiB of which 6.28 GiB is free. Process 2834 has 434.64 MiB memory in use. Including non-PyTorch memory, this process has 16.07 GiB memory in use. Of the allocated memory 8.47 GiB is allocated by PyTorch, and 7.20 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by HanLab-OSU** [comment]
Reducing the batch_size from 256 to 8 or 128 worked for me.
